### PR TITLE
LaTeX in docs.

### PR DESCRIPTION
**Pull request by amitjamadagni**
An attempt at integrating formula in docs.

### CODE REVIEW

**Comment by acroy** [comment]
What is the status of this PR? Can we use formulas in the doc-strings?

**Comment by amitjamadagni** [comment]
Yup we could use the formulas in the doc strings, the output would be TeX.

**Comment by acroy** [comment]
Good. Then we should do it where appropriate. This can be closed I presume?

**Comment by amitjamadagni** [comment]
Yup ! I guess we have an issue tracking this : https://github.com/JuliaQuantum/QuDynamics.jl/issues/5, so closing this.

**Pull request closed without merging**
