### PR TITLE
ODE Package updated, reflecting changes in README.

### PR DESCRIPTION
**Pull request by amitjamadagni**
Travis integration edited, dropped `Pkg.checkout("ODE")`.

### CODE REVIEW

**Comment by amitjamadagni** [comment]
Tests passing ! Merging this !

**Comment by acroy** [comment]
Might be good to update REQUIRE as well to indicate that ODE 0.2.1 is required.

**Comment by amitjamadagni** [comment]
@acroy does mentioning `ODE` in  `REQUIRE` pull the latest stable version ? In sense we  have edited travis integration as well and the tests seem to pass with this config. Please do let me know if I am missing something here.

EDIT : This shows up in travis, so I guess may be the version number need not be included.
`INFO: Installing ODE v0.2.1`

**Comment by acroy** [comment]
The REQUIRE file tells the package manager about the dependencies, so it can install a new version if necessary. If you have an older version of ODE already installed, you want to make sure that it is at least 0.2.1 when you try to install QuDynamics. This is what the version number is good for.

**Pull request merged**
