### PR TITLE
Add Travis support and fix REQUIRE.

### PR DESCRIPTION
**Pull request by acroy**

### CODE REVIEW

**Comment by acroy** [comment]
Interesting, the failure for julia nightly seems to be due to QuBase. We will need to have a look; cc: @jrevels.

@amitjamadagni : There is also a warning regarding Docile. I think we have to add something to check the version of Julia and only load it for 0.3.

**Comment by amitjamadagni** [comment]
@acroy I am going through https://github.com/MichaelHatherly/Docile.jl/issues/79
and http://julia.readthedocs.org/en/latest/manual/documentation/. In 0.4 there is an additional `doc` after the `@doc` macro, that is a bit confusing, but I guess we could work around on this.

**Comment by acroy** [comment]
@amitjamadagni : I got it and also fixed some other warnings. The other stuff has to be fixed upstream.

**Comment by amitjamadagni** [comment]
:+1: Tests pass :). Is this ready to go ?

**Comment by acroy** [comment]
I would think so.

**Pull request merged**
